### ISSUE TITLE
isSupported

### ISSUE THREAD

**Issue by caspahouzer** [hansemannn/titanium-review-dialog#1]
Hey,

if I ask for _isSupported_ OR ask for 10.3 myself, the review dialog is shown. But when I select the stars, I can't send the review. Do you know why?

Does the version has to match the version number in the app store? Or may not be beta or something?

**Comment by hansemannn** [comment]
That's all handled internally. You cannot use it in Simulator and probably also not on non-distribution-provisioned devices. Please try a Test-Flight build and ensure you didn't review before. No idea what Apple thought when doing that API. There is no error-handling, no events and no official "supported" method.
