### ISSUE TITLE
isSupported() return null

### ISSUE THREAD

**Issue by nicolomonili** [hansemannn/titanium-review-dialog#2]
I tried with Simulator (iOS 10.3) and with an iPhone 6s (iOS 10.3.1)
The method isSupported() return null.

**Comment by hansemannn** [comment]
Whoops! Here we go: [v1.0.1](https://github.com/hansemannn/titanium-review-dialog/releases/tag/v1.0.1) 🚀

**Comment by nicolomonili** [comment]
Yes, with 1.0.1 it's ok!
