### ISSUE TITLE
Clarified docs on using this module

### ISSUE THREAD

**Issue by skypanther** [hansemannn/titanium-review-dialog#5]
First, thanks for this module!

I had to do some digging to figure out the best way to use this module to be in keeping with Apple's recommendations. While looking into it, I found that your example here differs a bit from the Appcelerator blog post and from the Hyperloop examples repo. And none fully capture Apple's recommendations.

So, here goes my take ... according to [Apple's docs](https://developer.apple.com/documentation/storekit/skstorereviewcontroller/requesting_app_store_reviews):

* The SKStoreReviewController itself will decide when, or if, to show the prompt.
* You should not show it more than once for a given version of your app
* You should not show the dialog in response to user actions (like after a user clicks a button).
* You should not show it on first app launch (even after an update) but should wait until the user has used your app for a "meaningful" amount. 

With that in mind, here's a snippet of code that illustrates what I came up with for my app. It relies on the [semver module](https://github.com/smclab/ti-semver) / http://gitt.io/component/semver to compare app versions. Apple's own example uses a simple launch count to determine "meaningful" amount of use, which I've gone with here in this sample. You should use something appropriate for your app (amount of time, completion of an action N times, etc.)

```javascript
// first, check that the user has used your app for a "meaningful" amount
// here, a simple count of some action
var countOfSomeUserAction = Ti.App.Properties.getInt('countOfSomeUserAction', 0);
countOfSomeUserAction += 1;
Ti.App.Properties.setInt('countOfSomeUserAction', countOfSomeUserAction);
if (countOfSomeUserAction >= 4) {
  // if they've done whatever action 4 or more times, check the app version
  var semver = require('./semver');
  var lastVersionPromptedForReview = Ti.App.Properties.getString('lastVersionPromptedForReview', '1.0.0');
  var appVersion = Ti.App.version;
  var appVersionAsArray = appVersion.split('.');
  if (appVersionAsArray.length > 3) {
    // the semver library supports max 3-part version numbers (per semver rules)
    appVersion = appVersionAsArray[0] + '.' + appVersionAsArray[1] + '.' + appVersionAsArray[2];
  }
  if (semver.gt(appVersion, lastVersionPromptedForReview)) {
    // if the current app version is greater-than the last time you prompted them
    // prompt them with the titanium-review-dialog alert
    Ti.App.Properties.setString('lastVersionPromptedForReview', appVersion);
      var Review = require('ti.reviewdialog');
      if (Review.isSupported()) {
          Review.requestReview();
      }
  }
}
```

It would probably be helpful to others if you clarified the readme with the above info.

**Comment by hansemannn** [comment]
Thanks @skypanther, happy to hear from you btw! I've added it via https://github.com/hansemannn/titanium-review-dialog/commit/32c2507f903749bc12b5d446417689d8382c59df.
