### ISSUE TITLE
iOS app store connect beta builds does not show review modal

### ISSUE THREAD

**Issue by capsizeno4** [hansemannn/titanium-review-dialog#6]
Hi Hans,

I've added the module to our app, and when running it in development environment, it pops up, I can hit the stars, but it wont let me proceed.  Expected, as I saw your note in an earlier issue that this is how Apple set it up, that you have to be in production to submit the rating and review. 

However, when I post to App Store Connect as beta build and download from testflight, it doesn't fire at all.  I thought this was "production", but do I need to run this as a full approved release to actually see it in full action?

Thanks!

**Comment by hansemannn** [comment]
Please reach out to TiSlack for questions as this is clearly no bug.
