### ISSUE TITLE
Xcode 11.5

### ISSUE THREAD

**Issue by mattberg** [hansemannn/titanium-review-dialog#7]
I just recently updated to Xcode 11.5. Using the simulator, this works as expected. When I put my final App Store build on my device for testing (via Test Flight), it does not bring up the dialog at all. It was working fine on app release using previous Xcode. Any thoughts?

**Comment by hansemannn** [comment]
iOS decides when to prompt the dialog, so the system likely decided that it was prompted "enough for now" on your case. I hope it works again now! :-)
